### ISSUE TITLE
Invalid user claim - Azure AD

### ISSUE THREAD

**Issue by henrikmotzkus** [oidc-wp/openid-connect-generic#149]
Hi there,
want to authenticate by Azure AD with an Oauth2 v2 endpoint. I alway getting the error "invalid user claim" whatever I specifiy in "Identity key" or "Nickname key". What I'm doing wrong? Or do I misunderstand the settings?
Thanks
Henrik  
p.s. Here I have the documentation of the supported user claims: https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens

**Comment by amysticool** [comment]
Hello @henrikmotzkus did you find any solution ? have the same problem. 

Thanks

**Comment by henrikmotzkus** [comment]
Unfortunately not. Can the developer help?

**Comment by KrzychuR** [comment]
@henrikmotzkus 
1. Define OpenId scope like this: 'openid email profile offline_access'
2. Identity key -> use 'sub'
3. For a nickname -> 'name'
It works for me with Azure AD B2C version

One more thing, in Azure AD B2C configuration you can select which claims will be returned.

**Comment by henrikmotzkus** [comment]
@KrzychuR : Thanks, now I'm one step further. 

Now Azure AD B2C redirects me to the alternate redirect url (https://sitename/openid-connect-authorize). 

But wordpress returns a 404. 

Wordpress runs on a Azure App Service

**Comment by KrzychuR** [comment]
Hi @henrikmotzkus,

To be honest, I've dropped this idea for now. In my case (at this moment) I don't need to login user into WP base on B2C credentials nor syncing WP users with B2C.
I'm working on dedicated JS plugins for WP (and.. any other CMS). I just need access-token generated by B2C to be able to access mine API. For this purpose I have WP site and API on AzureAppServices and I've configured authentication base on Azure resources only. So in short I'm using `my-domain.org/.auth/me` enpoint to receive correct tokens :)

**Comment by timnolte** [comment]
@henrikmotzkus it seems according to a couple of responses on the [WordPress.org Support forums](https://wordpress.org/support/topic/azure-ad-redirect-url/) that there is a plugin setting to change the endpoint to the alternate redirect URL.

**Comment by timnolte** [comment]
For anyone else having problems I got this all working making sure to set the Identity Key to `upn` and I also opted to set the Nickname to `upn` also. I'm currently having problems authenticating guest users through Azure AD and so I'm working with an Azure AD admin to figure this out. With the `upn` setting users are able to login via SSO and have it connected to their existing account or a new account is provisioned.

**Comment by timnolte** [comment]
I Wanted to provide an update since we had problems with guest logins. After reading through the documentation here: 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc

I was able to get a proper configuration that works with Azure AD. If you pull up the "Discover Document" using:

https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration

All of the endpoints and the available claims information will be available. These are the settings that worked:

- OpenID Scope -> `openid profile email`
- Login Endpoint URL -> `https://login.microsoftonline.com/{tenant}/oauth2/authorize`
- Userinfo Endpoint URL -> `https://login.microsoftonline.com/{tenant}/openid/userinfo`
- Token Validation Endpoint URL -> `https://login.microsoftonline.com/{tenant}/oauth2/token`
- End Session Endpoint URL -> `https://login.microsoftonline.com/{tenant}/oauth2/logout?client_id={client-id}`
- Identity Key -> `unique_name`
- Nickname Key -> `name`
- Email Formatting -> `{unique_name}`
- Display Name Formatting -> `{name}`

Logout of WordPress successfully logs out the session within Azure AD also.

@daggerhart wondering if we can get the Wiki going on here so that we can start setting up some documentation for various implementations that have been successfully setup.

**Comment by daggerhart** [comment]
Wiki is a great idea. It's enabled on the repo, but I could spend an hour or so this weekend putting some pages up.

**Comment by timnolte** [comment]
Wanted to provide a good reference resource for testing and validating the Azure AD OpenID configuration. https://blogs.aaddevsup.xyz/2019/07/retrieving-user-information-from-azure-ads-userinfo-endpoints/

**Comment by timnolte** [comment]
Another bit of interesting information. Apparently there are differences in the data included(and the field names) between the v1 and v2 APIs. You can see the differences in this document: https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens

When I attempted to use the v1 API I had to set my **Identity Key** to `email` and my **Email Formatting** likewise to `{email}`.
