### ISSUE TITLE
accessing openid-connect-generic-last-id-token-claim upon user creation

### ISSUE THREAD

**Issue by eriksays** [oidc-wp/openid-connect-generic#240]
A question on matching AD user roles to wordpress roles upon user creation.

My azure AD application is sending a users AD groups as part of the id_token, and not the access_token

It seems the id_token is stored as the user meta 'openid-connect-generic-last-id-token-claim' upon user creation'

however, this does not seem to be available when using add_action('openid-connect-generic-user-create

Any thoughts on accessing 'openid-connect-generic-last-id-token-claim' upon user creation?

Thanks

**Comment by timnolte** [comment]
@eriksays yes, this is currently a limitation as I've worked through this issue for a client recently. I just added a [Wiki page](https://github.com/oidc-wp/openid-connect-generic/wiki/Azure-AD-Role-Mapping) with details on how to manage user role mapping with Azure AD that I have working. It's not the ideal solution but it does work.

**Comment by eriksays** [comment]
@timnolte thanks for your response.

I resolved this issue by using the 'wp-login' action
`function map_role_to_user($user_login, $user) {
    //do stuff
    assign_user_roles($user);
   
}

add_action('wp_login', 'map_role_to_user', 10, 2);`

The 'assign_user_roles($user) function would use: $user_claim = get_user_meta($uid, 'openid-connect-generic-last-id-token-claim'), same as your example code, to get the group permissions I needed. Once I got that, I mapped to the appropriate wordpress role. 

This worked on user creation and subsequent login.

**Comment by timnolte** [comment]
@eriksays I'm assuming you mean the `wp_login` action hook. I'm assuming you are having to still logout/login the user after updating their roles just like I did right? I'm not seeing where the new roles would be applied at this point. I need to trace back where `wp_signon()` is called so perhaps the user will get the new roles. I'm wondering if the `authenticate` filter(https://developer.wordpress.org/reference/hooks/authenticate/) would be more appropriate since it happens right before final login. If using the `wp_login` action hook is actually updating the roles for the user's current session that would be great and much more preferred than my solution of having to logout/login the user.

**Comment by eriksays** [comment]
@timnolte on testing, the wp_login action hook did update the role for the current session.
