### ISSUE TITLE
Users not being redirected to page where they clicked login link

### ISSUE THREAD

**Issue by jasonpierson** [oidc-wp/openid-connect-generic#257]
I've installed version 3.8.0 on WP 5.6 running PHP 7.3.9. Its on the main site(Awana) of a multisite network.

"Redirect Back to Origin Page" is checked in the plugin settings, but users are being redirected to the home page instead of the page they were previously on.

Steps to reproduce:
1. Go to **https://oid-connect-awananetwork.pantheonsite.io/shop**
2. Click on the **Login** link in the upper right corner
3. Log in. Username: **awanatestaccount@mailinator.com** Password: **.:g.t27'=pWpERYCJP5e**
Notice you are directed to https://oid-connect-awananetwork.pantheonsite.io/ instead of https://oid-connect-awananetwork.pantheonsite.io/shop

I am not using `openid-connect-generic-cookie-redirect-url` to change the redirect URL. The only hook I'm using is the shortcode for the login link: `esc_url(do_shortcode( '[openid_connect_generic_auth_url]' ));`

The issue appears to be in the `handle_redirect_login_type_auto` function in `/includes/openid-connect-generic-login-form.php`. The statement `if ( 'wp-login.php' == $GLOBALS['pagenow'] && ( 'auto' == $this->settings->login_type || ! empty( $_GET['force_redirect'] ) ) && ( ! isset( $_GET['action'] ) || 'logout' !== $_GET['action'] ) && ! isset( $_POST['wp-submit'] ) ) {` evaluates to false and so the `openid-connect-generic-redirect` cookie never gets set.

$GLOBALS['pagenow'] will never be `wp-login.php` b/c the login link is on each site page. We do not direct users to wp-login.php to log in.

I've made the awanatestaccount@mailinator.com user an administrator. oid-connect-awananetwork.pantheonsite.io is a sandbox; so feel free to blow it up if you need to. ;-)

**Comment by timnolte** [comment]
@jasonpierson I have a fixed ready for deployment related to this code you've mentioned, which fixes a password protected post login issue. I'm going to see about addressing this issue as well.

**Comment by jasonpierson** [comment]
@timnolte Great! Do you have any idea on a timeline for release?

**Comment by timnolte** [comment]
@jasonpierson so I was having a lot of problems with my Dev machine and just got a new machine last week and needed to make the move over to it so my nights/weekend was pretty much taken up trying to get moved over. I have a release pending and so I'll probably look at getting that release out this week and I'm not sure if I'll be able to get this fix in. As I'm thinking about it if sites are configured for "auto" SSO but the login is somewhere else then I think we have a problem. It seems like this should be working since I have a variation of this used on [this site](https://www.atla.com/blog/) where you see the login to read link. I do have a little but of customization going on there as there may be multiple login links and their desire was to have the user take to that posts page not the blog page. You should be able to use the shortcode along with the URL redirect argument to have it set the redirect URL to the current page. The `handle_redirect_login_type_auto` would be strictly for the login page enforcing users to SSO. So given all of that I'm not sure there really is a fix required here other than perhaps some documentation/instruction revisions.

**Comment by jasonpierson** [comment]
Ok; I've been playing around with this a little and it looks like my problem might be further up the chain. The `get_authentication_url` function in `/includes/openid-connect-generic-client-wrapper.php` is not passed any data when any page on the site loads. If data was being passed, `$_REQUEST['redirect_to']` would be assigned the passed redirect url, `handle_redirect_cookie()` gets called and sets the value of `$_REQUEST['redirect_to']` to the `openid-connect-generic-redirect` cookie. 

I've added this block to the beginning of the `get_authentication_url` function to guarantee the cookie is set down the line:
```
if ( $this->settings->redirect_user_back ) {
	global $wp;
	if ( is_array($atts) )
		$atts['redirect_to'] = home_url( $wp->request );
	else
		$atts = array('redirect_to' => home_url( $wp->request ));
}
```
Obviously I shouldn't be changing the plugin. Is there a better way to do this or something I'm missing?

**Comment by timnolte** [comment]
@jasonpierson the latest release went out

**Comment by jasonpierson** [comment]
@timnolte got it. I changed this:
```
function get_login_url($login_url=false, $redirect=false) {
    return esc_url(do_shortcode( '[openid_connect_generic_auth_url]' ));
}
add_filter( 'login_url', 'get_login_url', 10, 2 );
```
to this:
```
function get_login_url($login_url=false, $redirect=false) {
    global $wp;
    return esc_url(do_shortcode( '[openid_connect_generic_auth_url redirect_to="'.home_url( $wp->request ).'" ]' ));
}
add_filter( 'login_url', 'get_login_url', 10, 2 );
```
and its working perfectly without making changes to the plugin code. Thank you!!!
