### ISSUE TITLE
Error: User identity is not linked to an existing WordPress user.

### ISSUE THREAD

**Issue by DeathStapler** [oidc-wp/openid-connect-generic#278]
I'm trying to figure out how to make this plugin work the want I need it to, without introducing more code to the equation.  I want to be able to create a Wordpress user, then have that person login with OpenID.

I have:
- "Link Existing Users" option checked 
- "Create user if does not exist" unchecked

I do not want to create a user if it doesn't already exist in Wordpress.

I know about the hooks and the work arounds to make it work the way I want to, but based on the settings I have, it should work as expected.  Is there a reason it doesn't?

**Comment by timnolte** [comment]
@DeathStapler I believe there have been some other reports that, depending on the IDP used, that combination you describe is not working. I believe there is a matching issue being caused because of what some IDPs are leaving out of their claims.

What is the IDP you are using?

The only thing I can offer at the moment is to turn on the create users feature and leverage the hooks to prevent a new user from actually being created.

**Comment by s-seitz** [comment]
Hi!
I encountered the same problem. IDP is Keycloak. Interestingly enough, if I tick "Create user if does not exist" and left "Link Existing Users" disabled, the User is created with a numbered prefix. So if "username" already exists, a "username2" is created and successfully logged in. After taking a short peek into the code, this is expected behaviour for this case.

As I guess, after looking into the code a bit further, you're mapping the identity of the user by first storing a openid-connect-generic-subject-identity entity to the user_meta_data and later on trying to match against it via a WP_User_Query.

Maybe this causes a race-condition (the serving sql cluster isolates READ-COMMITED)? Just guessed.

The users on the affected site are LDAP-based and are not allowed to sync back. I don't know if the user_meta_data can be updated at all in this case, or if that matters :)

If you need further testing on this bug, I'm happy to deliver.

Would you please give a hint, what you mean with " and leverage the hooks to prevent a new user from actually being created" ?

**Comment by lliming** [comment]
My team is using the configuration described in the OP, and it generally seems to be working for us. One issue we've had (cited in #247 ), is that the matching currently being performed is case-sensitive, so wordpress username "bob" and IDP preferred_username "Bob" do NOT match. If Identity Key is set to "email", neither "bob@GMail.com" nor "Bob@gmail.com" match "bob@gmail.com".  It took us a while to figure this out, particularly since it's not always easy (for the wordpress site admins) to know precisely what the IDP's attributes are going to look like for the person for whom we're creating the account. (Even if we ask the individual, they'll sometimes "correct" the case without telling us.)

**Comment by timnolte** [comment]
@lliming thanks for the additional details. I'll be looking to carve our some time to work on another bug fix release soon, and will see about addressing this issue and the related casing issue.

**Comment by milesimarco** [comment]
Same problem here,
it seems that link_existing_users is **triggered only when create users function is turned on**.
After the first linking, the actual code is working for previous users as expected, even if we disable "create users".

The point is this part of code:

`
\includes\openid-connect-generic-client-wrapper.php, L510
`

```
$subject_identity = $client->get_subject_identity( $id_token_claim );
$user = $this->get_user_by_identity( $subject_identity );

if ( ! $user ) {
	if ( $this->settings->create_if_does_not_exist ) {
		$user = $this->create_new_user( $subject_identity, $user_claim );
		if ( is_wp_error( $user ) ) {
			$this->error_redirect( $user );
		}
	} else {
		$this->error_redirect( new WP_Error( 'identity-not-map-existing-user', __( 'User identity is not linked to an existing WordPress user.', 'daggerhart-openid-connect-generic' ), $user_claim ) );
	}
} else {
	// Allow plugins / themes to take action using current claims on existing user (e.g. update role).
	do_action( 'openid-connect-generic-update-user-using-current-claim', $user, $user_claim );
}
```

On the first code run, the `get_user_by_identity` is checked against "sub" parameter only and returns null (users has not been linked):
```
/**
* Retrieve the subject identity from the id_token.
*
* @param array $id_token_claim The ID token claim.
*
* @return mixed
*/
public function get_subject_identity( $id_token_claim ) {
return $id_token_claim['sub'];
}
```

But after this check, the linking function is only called when `$this->settings->create_if_does_not_exist` is true.

**Comment by timnolte** [comment]
@milesimarco thanks for digging into that. I will be looking to get a new release out within the next few weeks as things slow for the holidays.

**Comment by mmmccain** [comment]
It does appear to be related to case sensitivity in the email address if that is helpful.
