### ISSUE TITLE
Invalid State upon Azure B2C Password Reset

### ISSUE THREAD

**Issue by rekkisomo** [oidc-wp/openid-connect-generic#332]
We've noticed an issue when a user resets their password via Azure AD B2C. Upon redirect after resetting, an `invalid-state` error appears and the user is forced to reset the password again when clicking on "Sign in with OpenID Connect". We're not really sure what's causing this, as it seems to be isolated with a select few of users, but any help or suggestions would help greatly!

Thanks!

**Comment by timnolte** [comment]
@rekkisomo this is most likely due to the fact that during a password reset operation there is extra time required to accomplish the password change before going back to the WordPress site. The state generated by the plugin defaults to a 3 minute lifetime before it expires. If a login process takes more time then that this will result in an invalid state error. If this seems to happen enough then you can extend the state limit in the plugin settings. This would explain why you are seeing it for a limited number of users.

**Comment by rekkisomo** [comment]
@timnolte thanks! Looks like increasing it 300 seconds has helped almost eradicate this issue. Is there any worrying security downsides of increasing this limit in production?

**Comment by timnolte** [comment]
@rekkisomo so the security implications of keeping that state valid too long is opening it up to replay attacks if the state is captured.

**Comment by rekkisomo** [comment]
@timnolte Thanks! I'll see what we can do. :)

**Comment by rekkisomo** [comment]
Unsure if it's related, but `request_new_tokens` is fired on each request made, despite the refresh token being set to 14 days (and access tokens set to 1hr) as default by Azure AD B2C.

Is this normal behaviour? It seems that in `ensure_tokens_still_fresh`, it shouldn't be requesting a new token if it's not expired. Azure's token endpoints are generally slow, so page loads and api requests when signed in take quite a while, compared to near-instant when signed out.
