### ISSUE TITLE
Post-Login Redirection Issues with LoginWP

### ISSUE THREAD

**Issue by adamboutcher** [oidc-wp/openid-connect-generic#408]
When using [LoginWP (Formerly Peter's Login Redirect)](https://en-gb.wordpress.org/plugins/peters-login-redirect/) to redirect users logging in, if they utilise oauth via the wp-login page, it doesn't redirect.

You do a check to see if request_url is set, however I believe it would never be actioned with the standard wordpress login flow and oauth; it may however work if you use the shortcodes.

I can fix it by editing the wrapper script and not redirecting to admin_url but to /?loginwp_link_redirect=true as documented on [LoginWP](https://loginwp.com/article/login-redirect-support-login-plugins/) however this feels a bit like a bodge and would be lost on update.

A fix could be that its a user config variable?

**Comment by timnolte** [comment]
Have you tried to use the Filter Hook that is available? https://github.com/oidc-wp/openid-connect-generic/wiki/Hooks---Actions-&-Filters#openid-connect-generic-auth-url

**Comment by timnolte** [comment]
Actually, sorry wrong Filter. I believe this is the one you want. https://github.com/oidc-wp/openid-connect-generic/wiki/Hooks---Actions-&-Filters#openid-connect-generic-client-redirect-to

**Comment by timnolte** [comment]
I'm not sure to what extent we're going to want to modify our plugin to accommodate other plugins' interception of handling the redirect, since our plugin is already attempting to do that, it's going to get really messy really fast. The problem is with SSO authentication we have to send the user somewhere else, and unless we have our own mechanism for sending a user to a known/expected destination after validation authentication then our plugin would be very frustrating for people that aren't trying to other login redirect stuff to use. This is where we do provide many hooks to customize how different things are handled. I'd be open to adding in a hook somewhere to accommodate the ability to customize this flow in order to provide the expected behavior.

**Comment by adamboutcher** [comment]
I'll have a play with the filter in the morning. I think the defaults are good but a configurable URL to override might be really handy.

**Comment by adamboutcher** [comment]
Thanks the "redirect-user-back" action worked.

For anyone with the same issue...

`// OAUTH Flow breaks WPLogin, this hooks into the flow if "Redirect back to Origin" is enabled in OAUTH
add_action('openid-connect-generic-redirect-user-back', function( $redirect_url, $user ) {
    wp_redirect( "/?loginwp_link_redirect=true" );
    exit();
}, 10, 2); `
