### ISSUE TITLE
Incompatability with "Maintenance" Plugin

### ISSUE THREAD

**Issue by adamboutcher** [oidc-wp/openid-connect-generic#409]
Not really an issue but incase others have problems.

The plugin [Maintenance](https://en-gb.wordpress.org/plugins/maintenance/) will cause issues with oauth logout redirects, it will completely remove the logout filter and so you never logout of the oauth provider.

**Comment by timnolte** [comment]
This would be better served as a Discussion topic as this doesn't sound like anything we can fix if another plugin is doing something out of our control.

**Comment by timnolte** [comment]
One other note is that maybe it would be helpful to add a plugin compatibility section to the Wiki, then we can have these sorts of items tracked there so it's easier for people to find solutions. Possibly a Discussion topic might work as well and be a bit more open. We could try the discussion route so that it's maybe even easier for people to submit and discuss the solutions.
