### ISSUE TITLE
Custom Login Form and Widget

### ISSUE THREAD

**Issue by backpackingseries** [oidc-wp/openid-connect-generic#423]
**Replace WP Login Form with Custom Form**

I currently use Login by Auth0 plugin. When I tried your plugin, I noticed that on the WP Login page, there’s a button “Login with OpenID Connect” placed just above the standard WP Login form. 

Instead, **similar to Lock form offered by Auth0**, itd be great if we could completely replace the WordPress login form with a custom form and a related WordPress widget.

PS: I'm primarily interested to see a custom form (SDK?) implementation for AWS Cognito.

Many thanks,

**Comment by timnolte** [comment]
@backpackingseries this plugin doesn't implement any sort of embedded form as all authentication is done at the IDP. There is already a short code that allows you to place the login button anywhere on your site.

**Comment by backpackingseries** [comment]
@timnolte Thanks and yes,  I am curious whether you might consider this as a feature request. 

WordPress implementations require frontend/UI flexibility. A hosted login page by (say) Cognito is good but restrictive. For instance, if you want to override the redirect URL after login, a custom plugin form can help. Multiple custom forms can be placed as login modals with varying shortcode attributes.

PS: This request is inspired by Auth0's Lock implentantation.

Kind regards,

**Comment by timnolte** [comment]
This plugin already supports a short code that provides a login button and the short code also provides an attribute that allows you to define the final redirect location.

Since Auth0 is providing the plugin and the IDP they can provide features that we can't as easily provide. Our plugin is intended to be a generic OpenID Connect client that can be used with any IDP that supports the OpenID Connect standard.

I will have to take a look at the OpenID Connect standards and see what facility there might possibly be for this however, it is highly likely that not many IDPs that support OpenID Connect may support it. There are additional OIDC authorization flows that may allow this but I know that not all IDPs support them.

**Comment by backpackingseries** [comment]
Thank you so much for the helpful explanation. 

If you have plans for a pro version of this plugin, perhaps such forms could be initially offered as an LTD and then subscription-based premium addons.

So, even if a generic form is not possible, I'd be happy to pick up the specific forms addon LTD for Cognito. 

Really appreciate this thread.

PS: I'm not an expert on this but I researched through to find out that Cognito's SDK implementation might be better than using AWS Amplify.

Kind regards,

**Comment by timnolte** [comment]
@backpackingseries there are no plans for anything paid. I am currently the main/sole maintainer on top of my full-time job and I have no capacity to support paid customers. Honestly, if people want a paid solution that does more automatically then one of the existing paid solutions/integrations by Auth0 or MiniOrange are already available. This plugin, while seeming generic, is geared more towards the developers that have a need for deep and flexible customization. It may seem lacking because of so many basic initial settings, however if you look at the number of hooks available, including an entire custom settings API it is actually very powerful. A couple examples of these are found here:
- https://github.com/oidc-wp/oidc-generic-button-text-addon
- https://github.com/oidc-wp/openid-connect-generic/wiki/Azure-AD-Role-Mapping
- https://github.com/timnolte/oidc-keycloak-sso

**Comment by backpackingseries** [comment]
Thank you @timnolte Yes, I am learning more about your awesome plugin gradually and thank you for putting this out for everyone.

Appreciate your support.

Kind regards,
