### ISSUE TITLE
Redirect Issue

### ISSUE THREAD

**Issue by JustinB2020** [oidc-wp/openid-connect-generic#481]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to '/wp-login.php'
2. Click on 'Login with OpenID Connect'
4. SSO logs in and page loads to "0"

![image](https://github.com/oidc-wp/openid-connect-generic/assets/76484703/373d74ba-c4f1-450b-a229-cb923b02ead5)

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only this plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- Website URL: 
- PHP Version:  
- WordPress Version: 6.02
- Plugin Version: 3.9.1
- Identity Provider: 
- Relevant Plugin Settings:

**Comment by timnolte** [comment]
@JustinB2020 there aren't enough details here to even begin to diagnose the issue.

**Comment by JustinB2020** [comment]
Hi @timnolte, 
aprox two weeks ago this issue started.

When I click "Login with OpenID Connect"
![image](https://github.com/oidc-wp/openid-connect-generic/assets/76484703/bcc9e6ec-4bd5-4299-94ca-169d7ffe54dc)

It redirects me to the SSO login UI. I complete the login process. (The SSO service shows successful Authentication). 

Once the SSO is validated it redirects me back to my WP page. When it redirects me the page loads with "0" 

![image](https://github.com/oidc-wp/openid-connect-generic/assets/76484703/256c378c-1c40-4d69-9ad4-a8847d67a729)


**OpenID Connect UI and Logs**


![image](https://github.com/oidc-wp/openid-connect-generic/assets/76484703/626216d2-35b5-4a53-a282-f5a31d3a06b3)

**Comment by timnolte** [comment]
@JustinB2020 so it looks like you are using Amazon Cognito with federation? Since there hasn't been a plugin update in some time what changed on your site 2 weeks ago? Additionally, did you follow the items indicated to troubleshoot shoot if it is a problem with the plugin alone or a conflict with another plugin?

Just to clarify all of these questions, and your description you just now provided should have been answered when opening up the issue, and is why there is guidance on all of this.

I will take a moment to test the plugin tonight in my testing environment, along with my test Amazon Cognito environment, to see if I can reproduce the issue with that much knowledge. Thanks.

**Comment by timnolte** [comment]
@JustinB2020 just confirming that my Amazon Cognito instance is authenticating with the my WordPress 6.1.1 testing site just fine, I don't use Federation with Cognito just the native Cognito authentication. I'm going to upgrade the site to WordPress 6.2 and confirm whether things still work.

**Comment by timnolte** [comment]
@JustinB2020 also confirmed that after upgrading to 6.2 the site is still functioning.

**Comment by JustinB2020** [comment]
Hi @timnolte, 
thank you for doing research on this. I was having this problem for the past several weeks. I uninstalled OpenID Connect, removed all the back end file and reinstalled it. Now it works.  

Really weird.

As a side note, this is an awsome plugin.  Great work on it.
