### ISSUE TITLE
incomplete-user-claim

### ISSUE THREAD

**Issue by sanojsniksah** [oidc-wp/openid-connect-generic#91]
hello daggerhart, 
i'm using version 3.3.1 of your openID connect generic client and am having a weird issue.

I have 2 WP sites all on ecs / rds 

Site A (nonprod) was setup first from scratch / fresh db(mysql)/ freshly installed plugins and everything works perfectly. SSO & plugin work as expected. 

Site B ( qa site ) is a dup/copy of site A. 

My setup for site B  was:
build & deploy docker image / ecs ( w/o the openid plugin installed )
copy the nonprod db to the qa db. ( changed a few urls ect .. nonprod > qa kinda stuff ) 
went through the wp setup screens and added the qa db. 
installed the openid plugin manually via  WP UI
and configured it accordingly and specifically for siteB ( qa ) 
(( I'm assuming, by re installing and updating the plugin config that it overwrote 
siteA sso info with siteB  sso info ( in the db ). Seemed like it did.. there were no errors and most the info was the same anyways.  )) 

So here's the issue. 
SiteB users that existed in the db when it was copied from nonprod to qa can auth fine. 
NEW users trying to login to site B for the first time cannot. Upon hitting the WP site, they are redirected for auth, which passes, but the handoff back to WP generates a error  :: 

Type: incomplete-user-claimDate: 2018-07-16 18:20:04User: 0URI : /wp-admin/admin-ajax.php?action=openid-connect-authorize&code=BWFcGL7EctgSE0J6asrdPeMO379ZnKum80GNtwAG&state=466174ce80ffaeaa9d9056dec9fd5b8a | object(WP_Error)#27314 (2) {   ["errors"]=>   array(1) {     ["incomplete-user-claim"]=>     array(1) {       [0]=>       string(21) "User claim incomplete"     }   }   ["error_data"]=>   array(1) {     ["incomplete-user-claim"]=>     array(5) {       ["sub"]=>       string(8) "smithr000"       ["lName"]=>       string(5) "Smith"       ["fName"]=>       string(4) "Ryan"       ["PERNR"]=>       string(8) "01036873"       ["sapuid"]=>       string(8) "SMITHR000"     }   } }
-- | --

Testing the auth connection from our SSO app to the WP site passes. And again existing users auth fine. 

As a test, i deleted a existing user that did work via the WP UI,
but then trying to login again with that user fails in the same way. ( can't re add ) 

I also tried to manually add the user back ( link existing users is checked ) but again even after the user was manually added, going through sso generated the incomplete error , just the same as a completely new first time user. 

Any ideas what might be the issue ?  or way to remedy ?

**Comment by cyxou** [comment]
Same problem here even for existing WordPress users.

**Comment by cyxou** [comment]
For me, the problem was in the "Display Name Formatting" field of the plugin settings. I used default "{given_name} {family_name}" which results in error for some of my users. Clearing this field solves the issue, but it surely may not be considered as a solution to a problem as the problem hides in the [format_string_with_claim](https://github.com/daggerhart/openid-connect-generic/blob/6917df262f3dfdd0d7b7f3172f6932188ee571f8/includes/openid-connect-generic-client-wrapper.php#L565) function. I am not experienced with WordPress to debug this function, so I leave it for the author to investigate, but I guess that the function fails due to missing claims in the JWT that are supposed to be there according to the contents of the "Display Name Formatting" field.

**Comment by CharlyRipp** [comment]
@cyxou - That was exactly the problem. Thank you!
Also had a typo on the Nickname Key, which caused the same issue but this made me look for it

**Comment by dfredell** [comment]
@cyxou Thanks for a link to the code. I modified my local php `./wp-content/plugins/daggerhart-openid-connect-generic/includes/openid-connect-generic-client-wrapper.php` and enhanced the error message so I could tell what field it was unhappy about: `'User claim incomplete: '.$format.'`
Turns out that for me it was mad at the `Email Formatting` field so I switched it from `{email}` to `email` and it worked.

**Comment by Piland01** [comment]
Hello - am on 2025.10.1 and now am getting same Bad ID token claim error. Previously on 2025.2.4 i was able to overcome same error by using Email Formatting [email] and Display Name Formatting [blank] and it worked, but now same values gives error
